# Generated by Django 5.2.5 on 2026-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("resources", "0002_resource_slug_alter_resource_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="resources",
                to="courses.course",
                verbose_name="Target Courses",
            ),
        ),
    ]
