# Generated by Django 5.2.5 on 2026-01-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_contact_secondary',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Secondary Contact'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_contact',
            field=models.CharField(max_length=15, verbose_name='Primary Contact'),
        ),
    ]
