# Generated by Django 5.2.5 on 2026-01-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_parent_contact_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='former_high_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID Number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(default='Kenyan', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Enrollment Date'),
        ),
    ]
