# Generated by Django 5.2.5 on 2026-01-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_former_high_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_fully_paid',
        ),
    ]
