# Generated by Django 5.2.5 on 2026-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_contact',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_contact_secondary',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_primary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_secondary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
