# Generated by Django 5.2.5 on 2026-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_cohort_studentprofile_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="graduation_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="graduation_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending Review"),
                    ("Eligible", "Eligible for Graduation"),
                    ("Not Eligible", "Not Eligible"),
                    ("Graduated", "Graduated"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="is_eligible_for_graduation",
            field=models.BooleanField(default=False),
        ),
    ]
