# Generated by Django 5.2.5 on 2026-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_room_timetable_unit_alter_timetable_course_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="timetable",
            name="unit_type",
            field=models.CharField(
                choices=[("core", "Core Unit"), ("common", "Common Unit")],
                default="core",
                max_length=10,
                verbose_name="Unit Type",
            ),
        ),
    ]
