# Generated by Django 5.2.5 on 2026-01-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_coursefee'),
        ('timetable', '0002_timetable_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='finance.coursefee'),
        ),
    ]
